# Generated by Django 4.1.5 on 2023-02-06 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDietStyle',
            fields=[
                ('diet_style_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_style_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeDifficultyLevel',
            fields=[
                ('difficulty_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('prep_time', models.TimeField()),
                ('cook_time', models.TimeField()),
                ('yield_servings', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diet_style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipedietstyle')),
                ('difficulty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipedifficultylevel')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_text', models.CharField(max_length=1000)),
                ('instruction_img_url', models.CharField(max_length=255)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipepost')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=1000)),
                ('comment_img_url', models.CharField(max_length=255)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipepost')),
            ],
        ),
    ]
