# Generated by Django 4.1.5 on 2023-02-07 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipecomments_comment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomments',
            name='comment_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipecomments',
            name='comment_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='instruction_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='instruction_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='cook_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='diet_style_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.recipedietstyle'),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='prep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='recipe_img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='yield_servings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
