# Generated by Django 4.1.5 on 2023-02-11 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0004_remove_recipepost_cook_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipePost',
            new_name='Recipe',
        ),
    ]
